#!/bin/sh
#
# A hook script to auto fix all PHP files to follow standards desribed in .php_cs file.
# Called by "git commit" with no arguments.
# The hook should exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# Redirect output to stderr.
exec 1>&2

echo "php-cs-fixer pre commit hook start\n"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
	HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
	FILES=` git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | tr '\n' ' '`
	if [ -z "$FILES" ]
	then
		echo "PHP files not found."
	else
		$PHP_CS_FIXER fix --allow-risky=yes --verbose ${FILES} --config=.php-cs-fixer.php
		git add ${FILES}
	fi
else
	echo "Please install php-cs-fixer, e.g.:\n"
	echo "composer require friendsofphp/php-cs-fixer --dev\n"
fi

echo "php-cs-fixer pre commit hook finish\n"
